-- SQL schema reference. The executable source of truth remains Laravel migrations.
-- Production target: MySQL 8.
-- Generate a live dump with: mysqldump --no-data $DB_DATABASE > database/schema/mysql-schema.sql

CREATE TABLE tenants (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL UNIQUE, created_at TIMESTAMP NULL, updated_at TIMESTAMP NULL);
CREATE TABLE forms (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, public_token VARCHAR(40) NOT NULL UNIQUE, description TEXT NULL, schema JSON NOT NULL, settings JSON NULL, is_published TINYINT(1) NOT NULL DEFAULT 0, version INT UNSIGNED NOT NULL DEFAULT 1, published_at TIMESTAMP NULL, created_at TIMESTAMP NULL, updated_at TIMESTAMP NULL, deleted_at TIMESTAMP NULL);
CREATE TABLE form_versions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, form_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NULL, version INT UNSIGNED NOT NULL, change_summary VARCHAR(255) NULL, schema JSON NOT NULL, settings JSON NULL, created_at TIMESTAMP NULL, updated_at TIMESTAMP NULL);
CREATE TABLE submissions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL, form_id BIGINT UNSIGNED NOT NULL, form_version INT UNSIGNED NOT NULL, payload JSON NOT NULL, respondent_email VARCHAR(255) NULL, respondent_name VARCHAR(255) NULL, ip_hash VARCHAR(255) NULL, user_agent VARCHAR(255) NULL, completed_at TIMESTAMP NOT NULL, created_at TIMESTAMP NULL, updated_at TIMESTAMP NULL, FULLTEXT respondent_search (respondent_name, respondent_email));
CREATE TABLE ai_generations (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, tenant_id BIGINT UNSIGNED NOT NULL, form_id BIGINT UNSIGNED NULL, user_id BIGINT UNSIGNED NOT NULL, mode VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL DEFAULT 'queued', prompt TEXT NOT NULL, model VARCHAR(255) NULL, prompt_tokens INT UNSIGNED NOT NULL DEFAULT 0, completion_tokens INT UNSIGNED NOT NULL DEFAULT 0, latency_ms INT UNSIGNED NOT NULL DEFAULT 0, result_schema JSON NULL, error TEXT NULL, started_at TIMESTAMP NULL, finished_at TIMESTAMP NULL, created_at TIMESTAMP NULL, updated_at TIMESTAMP NULL);
